package models

type Food struct {
    Name string
    Synonyms string
    Category string
    Density string
    Reference_unit string
    Kilojoule int
    Kilocalories int
    Fat_g float32
    Saturated_fats_g string
    Monounsaturated_fats_g string
    Polyunsaturated_fats_g string
    Cholesterol_mg string
    Carbohydrates_g int
    Sugar_g string
    Starch_g string
    Dietary_fiber_g float32
    Protein_g float32
    Salt_nacl_g float32
    Alcohol_g string
    Water_g float32
    Vitamin_a_activity_re_mug_re string
    Vitamin_a_activity_rae_mug_re string
    Retinol_mug string
    Betacarotin_activity_mug_bce string
    Betacarotin_mug string
    Vitamin_b1_mg string
    Vitamin_b2_mg string
    Vitamin_b6_mg string
    Vitamin_b12_mug string
    Niacin_mg string
    Folat_mug string
    Vitamin_c_mg string
    Vitamin_d_mug string
    Vitamin_e_activity_mg_ate string
    Kalium_mg int
    Natrium_mg int
    Chlorid_mg string
    Calcium_mg int
    Magnesium_mg int
    Phosphor_mg int
    Iron_mg float32
    Iodine_mug string
    Zinc_mg float32
    Selenium_mug string
    Id int
}